---
systemd_defaults:
  scope: system
  profiles:
    simple:
      type: simple
      restart: on-failure
      enabled: true
    notify:
      type: notify
      restart: on-failure
      enabled: false
container_defaults:
  solution: podman
  images:
    node-exporter:
      registry: docker.io
      name: prom/node-exporter
      tag: latest
    prometheus:
      registry: docker.io
      name: prom/prometheus
      tag: latest
    alertmanager:
      registry: docker.io
      name: prom/alertmanager
      tag: latest
    grafana:
      registry: docker.io
      name: grafana/grafana
      tag: latest
    clickhouse:
      registry: docker.io
      name: clickhouse/clickhouse-server
      tag: latest
    nginx:
      registry: docker.io
      name: library/nginx
      tag: latest
  services: {}
conda_defaults:
  miniforge:
    url: https://github.com/conda-forge/miniforge/releases/latest/download
    script: Miniforge3-{{ ansible_system }}-{{ ansible_architecture }}.sh
    sources:
      - conda-forge
  reset: true
  envs:
    stable:
      - https://roq-trading.com/conda/stable
    unstable:
      - https://roq-trading.com/conda/unstable
  systemd:
    profile: notify
    timers: {}
  services: {}
roq_defaults:
  auth:
    public_key: YOUR_ROQ_PUBLIC_KEY
    secret_key: YOUR_ROQ_SECRET_KEY
  flags: {}
