---
systemd_defaults:
  scope: system
  user: '{{ ansible_user }}'
  group: '{{ ansible_user }}'
conda_defaults:
  url: https://github.com/conda-forge/miniforge/releases/latest/download
  script: Miniforge3-{{ ansible_system }}-{{ ansible_architecture }}.sh
  sources:
    - conda-forge
roq_defaults:
  auth:
    public_key: YOUR_ROQ_PUBLIC_KEY
    secret_key: YOUR_ROQ_SECRET_KEY
  systemd:
    services:
      restart: on-failure
      enabled: false
    timers: {}
  conda:
    envs:
      stable:
        - https://roq-trading.com/conda/stable
      unstable:
        - https://roq-trading.com/conda/unstable
  flags:
    shared: {}
  services: {}
