---
roq_defaults:
  dirs:
    run: /run/roq
    config: /usr/local/etc/roq
    data: /var/lib/roq
  service:
    user: ansible
    group: ansible
    start: '*-*-* 00:01:00'
    stop: '*-*-* 23:59:00'
    restart: 'no'
  conda:
    url: https://roq-trading.com/conda/unstable
  common:
    auth_keys:
      public_key: YOUR_ROQ_PUBLIC_KEY
      secret_key: YOUR_ROQ_SECRET_KEY
    flags:
      loop_sleep: 500ns
      loop_timer_freq: 2500ns
      event_log_iso_week: false
      event_log_symlink: true
      cache_mbp_checksum: false
      cache_all_reference_data: true
  services: {}
conda_defaults:
  url: https://github.com/conda-forge/miniforge/releases/latest/download
  script: Miniforge3-{{ "MacOSX" if ansible_os_family == "Darwin" else "Linux" }}-{{ ansible_architecture }}.sh
  sources:
    - conda-forge
