---

roq_coinbase_pro_defaults:
  version: "{{ roq_version }}"
  docker:
    use: "{{ roq_use_docker }}"
    name: "roqtrading/roq-coinbase-pro"
  service:
    start: "Sun *-*-* 00:01:00"
    stop: "Sat *-*-* 23:59:00"
  logging:
    verbosity: 0
  flags:
    name: "coinbase-pro"
    config_file: "{{ directory_config.usr_local_etc }}/roq/coinbase-pro/config.toml"
    event_log_dir: "{{ directory_config.var_lib }}/roq/data"
    client_listen_address: "{{ directory_config.run }}/roq/client/coinbase-pro.sock"
    service_listen_address: "{{ directory_config.run }}/roq/service/coinbase-pro.sock"
    auth_keys_file: "{{ directory_config.usr_local_etc }}/roq/keys.json"
    cache_dir: "{{ directory_config.var_lib }}/roq/cache"
    fix_uri: "tcp+ssl://fix-public.sandbox.pro.coinbase.com:4198"
    ws_uri: "wss://ws-feed-public.sandbox.pro.coinbase.com"
    rest_uri: "https://api-public.sandbox.pro.coinbase.com"
  symbols: ".*"
