---

roq_huobi_defaults:
  version: "{{ roq_version }}"
  docker:
    use: "{{ roq_use_docker }}"
    name: "roqtrading/roq-huobi"
  service:
    start: "Sun *-*-* 00:01:00"
    stop: "Sat *-*-* 23:59:00"
  logging:
    verbosity: 0
  flags:
    name: "huobi"
    config_file: "{{ directory_config.usr_local_etc }}/roq-huobi/config.toml"
    event_log_dir: "{{ directory_config.var_lib }}/roq/data"
    client_listen_address: "{{ directory_config.run }}/roq/roq-huobi.sock"
    metrics_listen_address: "{{ directory_config.run }}/roq/metrics/roq-huobi.sock"
    auth_keys_file: "{{ directory_config.usr_local_etc }}/roq/keys.json"
    auth_cache_dir: "{{ directory_config.var_lib }}/roq/cache"
    rest_uri: "https://api.huobi.pro"
    ws_market_uri: "wss://api.huobi.pro/ws"
    ws_mbp_uri: "wss://api.huobi.pro/feed"
    ws_order_uri: "wss://api.huobi.pro/ws/v2"
  symbols:
    - ".*"
