---

- block:

  - name: install conda package
    shell: "{{ directory_config.opt }}/conda/bin/mamba install -y -n base sqlite"
  
  become: "{{ 'true' if become_user is defined else 'false' }}"
  tags:
    - sqlite
