---

- block:

  - name: create directories
    file:
      path: "{{ item }}"
      state: directory
      owner: root
      group: root
      mode: 0755
    with_items:
      - "{{ directory_config.usr_local_etc }}/clickhouse"
    notify:
    - restart clickhouse

  - name: create directories (ownership managed by docker image)
    file:
      path: "{{ item }}"
      state: directory
    with_items:
      - "{{ directory_config.var_lib }}/clickhouse"
    notify:
    - restart clickhouse

  - name: create server config
    template:
      src: "templates/{{ item }}"
      dest: "{{ directory_config.usr_local_etc }}/clickhouse/{{ item }}"
      owner: root
      group: root
      mode: 0644
    with_items:
      - "server_config.xml"
      - "users.xml"
    notify:
    - restart clickhouse

  - name: pull images
    containers.podman.podman_image:
      name: "{{ docker_registry }}/{{ clickhouse_config.docker.name }}-{{ item }}"
      tag: "{{ clickhouse_config.docker.tag }}"
    with_items:
      - "server"
      - "client"
    notify:
    - restart clickhouse

  - name: create systemd service
    template:
      src: "templates/clickhouse-server.service"
      dest: "/etc/systemd/system/clickhouse-server.service"
      owner: root
      group: root
      mode: 0644
    register: clickhouse_service
    notify:
    - restart clickhouse

  - name: enable the clickhouse service
    systemd:
      name: "clickhouse-server.service"
      state: restarted
      enabled: true
      daemon_reload: true
    when: clickhouse_service.changed

  - name: create shell script
    template:
      src: "templates/clickhouse-client"
      dest: "{{ directory_config.usr_local_bin }}/clickhouse-client"
      owner: "{{ roq_user }}"
      mode: 0755

  become: "{{ 'true' if become_user is defined else 'false' }}"
  tags:
    - clickhouse
