---

- hosts: all
  pre_tasks:
    - name: check ansible minimum required version
      assert:
        that: "ansible_version.full is version_compare('2.7', '>=')"
        msg: >
          "You should use an updated version of Ansible, version 2.7 or higher is required"

- hosts: all
  roles:
    - config
    - baseline
    - kernel
    - python
    - podman

- hosts: trading,web
  roles:
    - conda
    - sqlite
    - roq-tools

- hosts: clickhouse
  roles:
    - clickhouse

- hosts: roq_clickhouse
  roles:
    - roq-clickhouse

- hosts: redis
  roles:
    - redis

- hosts: roq_pubsub
  roles:
    - roq-pubsub

- hosts: roq_json_bridge
  roles:
    - roq-json-bridge

- hosts: roq_fix_bridge
  roles:
    - roq-fix-bridge

- hosts: roq_binance
  roles:
    - roq-binance

- hosts: roq_binance_futures
  roles:
    - roq-binance-futures

- hosts: roq_bitfinex
  roles:
    - roq-bitfinex

- hosts: roq_bitmex
  roles:
    - roq-bitmex

- hosts: roq_bitstamp
  roles:
    - roq-bitstamp

- hosts: roq_bybit_v5
  roles:
    - roq-bybit-v5

- hosts: roq_coinbase_pro
  roles:
    - roq-coinbase-pro

- hosts: roq_deribit
  roles:
    - roq-deribit

- hosts: roq_ftx
  roles:
    - roq-ftx

- hosts: roq_gate
  roles:
    - roq-gate

- hosts: roq_gate_futures
  roles:
    - roq-gate-futures

- hosts: roq_gemini
  roles:
    - roq-gemini

- hosts: roq_hitbtc
  roles:
    - roq-hitbtc

- hosts: roq_huobi
  roles:
    - roq-huobi

- hosts: roq_huobi_futures
  roles:
    - roq-huobi-futures

- hosts: roq_kraken
  roles:
    - roq-kraken

- hosts: roq_kraken_futures
  roles:
    - roq-kraken-futures

- hosts: roq_kucoin
  roles:
    - roq-kucoin

- hosts: roq_kucoin_futures
  roles:
    - roq-kucoin-futures

- hosts: roq_okx
  roles:
    - roq-okx

- hosts: trading
  roles:
    - prometheus
    - grafana

- hosts: all
  roles:
    - nginx
