---
- hosts: all
  roles:
    - config  # create configurations (merge with defaults)
    - common  # create directories
    - container  # install containers
    - conda  # install conda
    - services  # install roq services
