---

roq_license_manager_defaults:
  version: "{{ roq_version }}"
  docker:
    use: "{{ roq_use_docker }}"
    name: "roqtrading/roq-license-manager"
  service:
    start: "Sun *-*-* 00:01:00"
    stop: "Sat *-*-* 23:59:00"
  logging:
    verbosity: 0
  flags:
    config_file: "{{ directory_config.usr_local_etc }}/roq-license-manager/config.toml"
    client_listen_address: "{{ directory_config.run }}/roq/roq-license-manager.sock"
