---

- block:

  - name: find list of gateways
    set_fact:                                                                                                                
       gateways: "{{ roq_config.gateways.keys() }}"

  - name: create required directories
    file:
      path: "/usr/local/etc/roq/{{ item }}"
      state: directory
    with_items: "{{ gateways }}"
  
  - name: create flags files
    template:                                                                                                                                                                 
      src: templates/flags.cfg
      dest: /usr/local/etc/roq/{{ item }}/flags.cfg
      owner: root                                                                                                       
      group: root                                                                                                       
      mode: 0644
    with_items: "{{ gateways }}"

  - name: create config files
    template:                                                                                                                                                                 
      src: templates/config.toml
      dest: /usr/local/etc/roq/{{ item }}/config.toml
      owner: root                                                                                                       
      group: root                                                                                                       
      mode: 0644
    with_items: "{{ gateways }}"
  
  become: true
  tags:
    - gateways
