---

roq_gate_futures_defaults:
  version: "{{ roq_version }}"
  docker:
    use: "{{ roq_use_docker }}"
    name: "roqtrading/roq-gate-futures"
  service:
    start: "Sun *-*-* 00:01:00"
    stop: "Sat *-*-* 23:59:00"
  logging:
    verbosity: 0
  flags:
    name: "gate-futures"
    config_file: "{{ directory_config.usr_local_etc }}/roq-gate-futures/config.toml"
    event_log_dir: "{{ directory_config.var_lib }}/roq/data"
    client_listen_address: "{{ directory_config.run }}/roq/roq-gate-futures.sock"
    service_listen_address: "{{ directory_config.run }}/roq/metrics/roq-gate-futures.sock"
    auth_keys_file: "{{ directory_config.usr_local_etc }}/roq/keys.json"
    cache_dir: "{{ directory_config.var_lib }}/roq/cache"
    rest_uri: "https://api.gateio.ws/api/v4"
    ws_uri: "wss://fx-ws.gateio.ws/v4/ws/usdt"
    api: "usdt"
  symbols:
    - ".*"
