---
- block:
    - name: create systemd service files
      template:
        src: templates/systemd.service
        dest: '{{ user_config.systemd_unit_dir }}/{{ item }}.service'
        mode: 0644
        owner: '{{ "root" if systemd_config.scope == "system" else ansible_user }}'
        group: '{{ "root" if systemd_config.scope == "system" else ansible_user }}'
      with_items: '{{ container_services }}'
    - name: enable/disable systemd services
      systemd:
        name: '{{ item }}.service'
        scope: '{{ systemd_config.scope }}'
        enabled: '{{ systemd_config.profiles[container_config.services[item].systemd.profile].enabled }}'
        daemon_reload: true
      with_items: '{{ container_services }}'
  become: '{{ systemd_config.scope == "system" }}'
  tags:
    - container
