---

- name: combine user configuration with defaults
  set_fact:
    roq_bybit_v5_config: >
        {{ roq_bybit_v5_defaults | combine(roq_bybit_v5 | default({}), recursive=True) }}
    cacheable: true
  tags:
    - always

- block:

  - name: shorter variable name for config
    set_fact:
      config: "{{ roq_bybit_v5_config }}"

  - name: install
    include_role:
      name: common
      tasks_from: gateway

  when: "'roq_bybit_v5' in group_names"
  tags:
    - roq-bybit_v5
