---

roq_gate_defaults:
  version: "{{ roq_version }}"
  docker:
    use: "{{ roq_use_docker }}"
    name: "roqtrading/roq-gate"
  service:
    start: "Sun *-*-* 00:01:00"
    stop: "Sat *-*-* 23:59:00"
  logging:
    verbosity: 0
  flags:
    name: "gate"
    config_file: "{{ directory_config.usr_local_etc }}/roq-gate/config.toml"
    event_log_dir: "{{ directory_config.var_lib }}/roq/data"
    client_listen_address: "{{ directory_config.run }}/roq/roq-gate.sock"
    metrics_listen_address: "{{ directory_config.run }}/roq/metrics/roq-gate.sock"
    auth_keys_file: "{{ directory_config.usr_local_etc }}/roq/keys.json"
    cache_dir: "{{ directory_config.var_lib }}/roq/cache"
    rest_uri: "https://api.gateio.ws/api/v4"
    ws_uri: "wss://api.gateio.ws/ws/v4/"
  symbols:
    - ".*"
