---

roq_gemini_defaults:
  version: "{{ roq_version }}"
  docker:
    use: "{{ roq_use_docker }}"
    name: "roqtrading/roq-gemini"
  service:
    start: "Sun *-*-* 00:01:00"
    stop: "Sat *-*-* 23:59:00"
  logging:
    verbosity: 0
  flags:
    name: "gemini"
    config_file: "{{ directory_config.usr_local_etc }}/roq/gemini/config.toml"
    event_log_dir: "{{ directory_config.var_lib }}/roq/data"
    client_listen_address: "{{ directory_config.run }}/roq/client/gemini.sock"
    service_listen_address: "{{ directory_config.run }}/roq/service/gemini.sock"
    auth_keys_file: "{{ directory_config.usr_local_etc }}/roq/keys.json"
    cache_dir: "{{ directory_config.var_lib }}/roq/cache"
    fix_mkt_uri: "tcp://3.220.21.165:1514"
    fix_ord_uri: "tcp://3.220.21.165:1514"
    fix_drp_uri: "tcp://3.220.21.165:1514"
  symbols:
    - ".*"
  market_data:
    sender: "TODO: INSERT YOUR SENDER COMPONENT ID HERE"
    target: "TODO: INSERT YOUR TARGET COMPONENT ID HERE"
  order_entry:
    sender: "TODO: INSERT YOUR SENDER COMPONENT ID HERE"
    target: "TODO: INSERT YOUR TARGET COMPONENT ID HERE"
  drop_copy:
    sender: "TODO: INSERT YOUR SENDER COMPONENT ID HERE"
    target: "TODO: INSERT YOUR TARGET COMPONENT ID HERE"
