---

roq_ftx_defaults:
  version: "{{ roq_version }}"
  docker:
    use: "{{ roq_use_docker }}"
    name: "roqtrading/roq-ftx"
  service:
    start: "Sun *-*-* 00:01:00"
    stop: "Sat *-*-* 23:59:00"
  logging:
    verbosity: 0
  flags:
    name: "ftx"
    config_file: "{{ directory_config.usr_local_etc }}/roq-ftx/config.toml"
    event_log_dir: "{{ directory_config.var_lib }}/roq/data"
    client_listen_address: "{{ directory_config.run }}/roq/roq-ftx.sock"
    service_listen_address: "{{ directory_config.run }}/roq/metrics/roq-ftx.sock"
    auth_keys_file: "{{ directory_config.usr_local_etc }}/roq/keys.json"
    cache_dir: "{{ directory_config.var_lib }}/roq/cache"
    ws_uri: "wss://ftx.com/ws"
    rest_uri: "https://ftx.com"
    fix_uri: "tcp+ssl://fix.ftx.com:4364"
  symbols:
    - ".*"
