---

roq_bitfinex_defaults:
  version: "{{ roq_version }}"
  docker:
    use: "{{ roq_use_docker }}"
    name: "roqtrading/roq-bitfinex"
  service:
    start: "Sun *-*-* 00:01:00"
    stop: "Sat *-*-* 23:59:00"
  logging:
    verbosity: 0
  flags:
    name: "bitfinex"
    config_file: "{{ directory_config.usr_local_etc }}/roq/bitfinex/config.toml"
    event_log_dir: "{{ directory_config.var_lib }}/roq/data"
    client_listen_address: "{{ directory_config.run }}/roq/client/bitfinex.sock"
    service_listen_address: "{{ directory_config.run }}/roq/service/bitfinex.sock"
    auth_keys_file: "{{ directory_config.usr_local_etc }}/roq/keys.json"
    cache_dir: "{{ directory_config.var_lib }}/roq/cache"
    rest_uri: "https://api-pub.bitfinex.com"
    ws_public_uri: "wss://api-pub.bitfinex.com/ws/2"
    ws_private_uri: "wss://api.bitfinex.com/ws/2"
  symbols:
    - ".*"
