# config file for the {{ item }} gateway

# symbols to subscribe from exchange
{{ roq_config.gateways[item].config.symbols | roq_toml_symbols }}
{%- if roq_config.gateways[item].config.accounts is defined %}

# exchange accounts
{{ roq_config.gateways[item].config.accounts | roq_toml_accounts }}
{%- endif %}
{%- if roq_config.gateways[item].config.users is defined %}

# clients (trading strategies)
{{ roq_config.gateways[item].config.users | roq_toml_users }}
{%- endif %}
{%- if roq_config.gateways[item].config.market_data is defined %}

# gemini, only
[market_data]
{% for (name, value) in roq_config.gateways[item].config.market_data.items() %}
  {{ name }} = "{{ value }}"
{% endfor %}
{%- endif %}
{%- if roq_config.gateways[item].config.order_entry is defined %}

# gemini, only
[order_entry]
{% for (name, value) in roq_config.gateways[item].config.order_entry.items() %}
  {{ name }} = "{{ value }}"
{% endfor %}
{%- endif %}

{%- if roq_config.gateways[item].config.drop_copy is defined %}

# gemini, only
[drop_copy]
{% for (name, value) in roq_config.gateways[item].config.drop_copy.items() %}
  {{ name }} = "{{ value }}"
{% endfor %}
{%- endif %}
