---
roq:
  auth:
    public_key: YOUR_ROQ_PUBLIC_KEY
    secret_key: YOUR_ROQ_SECRET_KEY
  systemd:
    start: '*-*-* 00:01:00'
    stop: '*-*-* 23:59:00'
    restart: 'on-failure'
  conda:
    envs:
      stable:
        - 'https://roq-trading.com/conda/stable'
      unstable:
        - 'https://roq-trading.com/conda/unstable'
  flags:
    shared:
      log:
        log_verbosity: 0
      loop:
        loop_sleep: 500ns
        loop_timer_freq: 2500ns
      gateway:
        auth_keys_file: '{{ user_config.config_dir }}/shared/keys.json'
        cache_all_reference_data: true
        cache_dir: '{{ user_config.cache_dir }}'
        cache_mbp_checksum: false
        event_log_dir: '{{ user_config.data_dir }}'
        event_log_iso_week: false
        event_log_symlink: true
  services:
    deribit:
      systemd:
        enabled: false
      conda:
        env: unstable
        package: roq-deribit
      client_listen_address:
        type: unix
      dependencies: []
      flags:
        package: test
        shared:
          - log
          - loop
          - gateway
        custom:
          # log_verbosity: 1
          loop_cpu_affinity: 1
      config:
        symbols:
          - ^BTC(_USD[A-Z]?)?-PERPETUAL$
          - ^ETH(_USD[A-Z]?)?-PERPETUAL$
        accounts:
          A1:
            login: YOUR_DERIBIT_PUBLIC_KEY
            secret: YOUR_DERIBIT_SECRET_KEY
            symbols: .*
            master: true
        users:
          test:
            password: '1234'
            symbols: .*
          trader:
            password: secret
            accounts: A1
            symbols: BTC-PERPETUAL
    bybit:
      systemd:
        enabled: false
      conda:
        env: unstable
        package: roq-bybit
      client_listen_address:
        type: unix
      dependencies: []
      flags:
        package: test
        shared:
          - log
          - loop
          - gateway
        custom:
          # log_verbosity: 1
          loop_cpu_affinity: 2
      config:
        symbols:
          - ^BTCUSD[A-Z]?$
          - ^ETHUSD[A-Z]?$
        accounts:
          A1:
            login: YOUR_BYBIT_PUBLIC_KEY
            secret: YOUR_BYBIT_SECRET_KEY
            symbols: .*
            master: true
        users:
          test:
            password: '1234'
            symbols: .*
          trader:
            password: secret
            accounts: A1
            symbols: BTCUSDT
    algo-1:
      systemd:
        enabled: false
      conda:
        env: unstable
        package: roq-cpp-algo-template
      dependencies:
        - deribit
        - bybit
      flags:
        shared:
          - log
          - loop
        custom:
          # log_verbosity: 1
          loop_cpu_affinity: 3
      config:
        strategy_id: 123
        legs:
          - source: 0
            account: A1
            exchange: deribit
            symbol: BTC-PERPETUAL
            time_in_force: gtc
          - source: 1
            account: A1
            exchange: bybit
            symbol: BTCUSD
            time_in_force: gtc
    fix-bridge:
      systemd:
        enabled: false
      conda:
        env: unstable
        package: roq-fix-bridge
      client_listen_address:
        type: tcp
        port: 1234
        interface: localhost
      dependencies:
        - deribit
      flags:
        shared:
          - log
          - loop
        custom:
          # log_verbosity: 1
          loop_cpu_affinity: 4
          init_missing_md_entry_type_to_zero: true
      config:
        symbols:
          - [USD.*, BTC.*]
          - deribit:
              - BTC-PERPETUAL
              - ETH-PERPETUAL
        users:
          md1:
            component: test
            username: md1
          oe1:
            component: test
            username: oe1
            password: secret
            account: A1
        statistics:
          FUNDING_RATE:
            fix_md_entry_type: PRIOR_SETTLE_PRICE
          PRE_SETTLEMENT_PRICE:
            fix_md_entry_type: SETTLEMENT_PRICE
            default_value: -1.23
    service-manager:
      systemd:
        enabled: false
      conda:
        env: unstable
        package: roq-service-manager
      client_listen_address:
        type: tcp
        port: 2345
        interface: localhost
      flags:
        shared:
          - log
        custom:
          # log_verbosity: 1
          scope: '{{ systemd_config.scope }}'
      config: {}
