---

- block:

  - name: create required directories
    file:
      path: "{{ item }}"
      state: directory
    with_items:
      - "/opt/conda"
  
  - name: download installer
    get_url:
      url: "{{ conda_config.url }}/{{ conda_config.script }}"
      dest: "/opt"
      mode: 0644
  
  - name: install
    shell: "bash /opt/{{ conda_config.script }} -b -u -p /opt/conda"
    args:
      creates: "/opt/conda/bin/activate"
  
  - name: create .condarc
    template:
      src: "templates/condarc"
      dest: "/opt/conda/.condarc"
      mode: 0644
  
  become: true
  tags:
    - conda
