---
- name: Conda
  tags:
    - conda
  become: '{{ config_systemd.scope == "system" }}'
  block:
    - name: Download installer
      ansible.builtin.get_url:
        url: '{{ config_conda.miniforge.url }}/{{ config_conda.miniforge.script }}'
        dest: /tmp/{{ config_conda.miniforge.script }}
        mode: 0644
    # XXX FIXME TOD keep old as backup
    - name: Remove old conda
      ansible.builtin.file:
        path: '{{ config_user.conda_dir }}'
        state: absent
    - name: Install conda
      ansible.builtin.shell: '{{ ansible_facts.env.SHELL }} /tmp/{{ config_conda.miniforge.script }} -b -u -p {{ config_user.conda_dir }}'
      args:
        creates: '{{ config_user.conda_dir }}/bin/activate'
    - name: Create conda environments
      ansible.builtin.shell: '{{ config_user.conda_dir }}/bin/conda create -n {{ item.key }} -y'
      args:
        creates: '{{ config_user.conda_dir }}/envs/{{ item.key }}'
      loop: '{{ config_packages | dict2items }}'
    - name: Install conda packages
      ansible.builtin.shell: '{{ config_user.conda_dir }}/bin/conda install --freeze-installed -y -n {{ item.key }} -c {{ config_conda.envs[item.key] | join(" -c ") }}
        {{ item.value | unique | join(" ") }}'
      loop: '{{ config_packages | dict2items }}'
    # all services
    - name: Create systemd service files
      ansible.builtin.template:
        src: templates/systemd.service
        dest: '{{ config_user.systemd_unit_dir }}/{{ item }}.service'
        mode: 0644
        owner: '{{ "root" if config_systemd.scope == "system" else ansible_user }}'
        group: '{{ "root" if config_systemd.scope == "system" else ansible_user }}'
      with_items: '{{ config_conda_all_services }}'
    - name: Create required directories
      ansible.builtin.file:
        path: '{{ config_user.config_dir }}/services/{{ item }}'
        state: directory
        mode: 0755
        owner: '{{ ansible_user }}'
        group: '{{ ansible_user }}'
      with_items: '{{ config_conda_all_services }}'
    - name: Create flags files
      ansible.builtin.template:
        src: templates/flags.cfg
        dest: '{{ config_user.config_dir }}/services/{{ item }}/flags.cfg'
        mode: 0644
        owner: '{{ ansible_user }}'
        group: '{{ ansible_user }}'
      with_items: '{{ config_conda_all_services }}'
    - name: Create config files
      ansible.builtin.template:
        src: '{{ "templates/config.toml" if item == "service-manager" else "templates/config.toml" }}'
        dest: '{{ config_user.config_dir }}/services/{{ item }}/config.toml'
        mode: 0644
        owner: '{{ ansible_user }}'
        group: '{{ ansible_user }}'
      with_items: '{{ config_conda_all_services }}'
    # user services
    - name: Create systemd start timer files
      ansible.builtin.template:
        src: templates/systemd.timer
        dest: '{{ config_user.systemd_unit_dir }}/{{ item }}.timer'
        mode: 0644
        owner: '{{ "root" if config_systemd.scope == "system" else ansible_user }}'
        group: '{{ "root" if config_systemd.scope == "system" else ansible_user }}'
      with_items: '{{ config_conda_user_services }}'
      when: '"start" in config_conda.systemd.timers'
    - name: Remove systemd start timer files
      ansible.builtin.file:
        path: '{{ config_user.systemd_unit_dir }}/{{ item }}.timer'
        state: absent
      with_items: '{{ config_conda_user_services }}'
      when: '"start" not in config_conda.systemd.timers'
    - name: Create systemd stop service files
      ansible.builtin.template:
        src: templates/systemd-stop.service
        dest: '{{ config_user.systemd_unit_dir }}/{{ item }}-stop.service'
        mode: 0644
        owner: '{{ "root" if config_systemd.scope == "system" else ansible_user }}'
        group: '{{ "root" if config_systemd.scope == "system" else ansible_user }}'
      with_items: '{{ config_conda_user_services }}'
      when: '"stop" in config_conda.systemd.timers'
    - name: Remove systemd stop service files
      ansible.builtin.file:
        path: '{{ config_user.systemd_unit_dir }}/{{ item }}-stop.service'
        state: absent
      with_items: '{{ config_conda_user_services }}'
      when: '"stop" not in config_conda.systemd.timers'
    - name: Create systemd stop timer files
      ansible.builtin.template:
        src: templates/systemd-stop.timer
        dest: '{{ config_user.systemd_unit_dir }}/{{ item }}-stop.timer'
        mode: 0644
        owner: '{{ "root" if config_systemd.scope == "system" else ansible_user }}'
        group: '{{ "root" if config_systemd.scope == "system" else ansible_user }}'
      with_items: '{{ config_conda_user_services }}'
      when: '"stop" in config_conda.systemd.timers'
    - name: Remove systemd stop timer files
      ansible.builtin.file:
        path: '{{ config_user.systemd_unit_dir }}/{{ item }}-stop.timer'
        state: absent
      with_items: '{{ config_conda_user_services }}'
      when: '"stop" not in config_conda.systemd.timers'
    - name: Enable/disable systemd services
      ansible.builtin.systemd:
        name: '{{ item }}.service'
        scope: '{{ config_systemd.scope }}'
        enabled: '{{ config_systemd.profiles[config_conda.systemd.profile].enabled }}'
        daemon_reload: true
      with_items: '{{ config_conda_user_services }}'
    - name: Enable systemd start timers
      ansible.builtin.systemd:
        name: '{{ item }}.timer'
        scope: '{{ config_systemd.scope }}'
        state: started
        enabled: true
        daemon_reload: true
      with_items: '{{ config_conda_user_services }}'
      when: '"start" in config_conda.systemd.timers'
    - name: Disable systemd stop services
      ansible.builtin.systemd:
        name: '{{ item }}-stop.service'
        scope: '{{ config_systemd.scope }}'
        enabled: false
        daemon_reload: true
      with_items: '{{ config_conda_user_services }}'
      when: '"stop" in config_conda.systemd.timers'
    - name: Enable systemd stop timers
      ansible.builtin.systemd:
        name: '{{ item }}-stop.timer'
        scope: '{{ config_systemd.scope }}'
        state: started
        enabled: true
        daemon_reload: true
      with_items: '{{ config_conda_user_services }}'
      when: '"stop" in config_conda.systemd.timers'
    # service-manager services
    - name: Enable/disable systemd services
      ansible.builtin.systemd:
        name: '{{ item }}.service'
        scope: '{{ config_systemd.scope }}'
        enabled: true
        daemon_reload: true
        state: started
      with_items: '{{ config_conda_service_manager_services }}'
