---
- block:
    - name: create conda environments
      shell: '{{ user_config.conda_dir }}/bin/conda create -n {{ item.key }} -y'
      args:
        creates: '{{ user_config.conda_dir }}/envs/{{ item.key }}'
      loop: '{{ packages | dict2items }}'
    - name: install conda packages
      shell: '{{ user_config.conda_dir }}/bin/conda install --freeze-installed -y -n {{ item.key }} -c {{ conda_config.envs[item.key] | join(" -c ") }} {{ item.value | unique | join(" ") }}'
      loop: '{{ packages | dict2items }}'
    # all services
    - name: create systemd service files
      template:
        src: templates/systemd.service
        dest: '{{ user_config.systemd_unit_dir }}/{{ item }}.service'
        mode: 0644
        owner: '{{ "root" if systemd_config.scope == "system" else ansible_user }}'
        group: '{{ "root" if systemd_config.scope == "system" else ansible_user }}'
      with_items: '{{ all_services }}'
    - name: create required directories
      file:
        path: '{{ user_config.config_dir }}/services/{{ item }}'
        state: directory
        mode: 0755
        owner: '{{ ansible_user }}'
        group: '{{ ansible_user }}'
      with_items: '{{ all_services }}'
    - name: create flags files
      template:
        src: templates/flags.cfg
        dest: '{{ user_config.config_dir }}/services/{{ item }}/flags.cfg'
        mode: 0644
        owner: '{{ ansible_user }}'
        group: '{{ ansible_user }}'
      with_items: '{{ all_services }}'
    - name: create config files
      template:
        src: '{{ "templates/config.toml" if item == "service-manager" else "templates/config.toml" }}'
        dest: '{{ user_config.config_dir }}/services/{{ item }}/config.toml'
        mode: 0644
        owner: '{{ ansible_user }}'
        group: '{{ ansible_user }}'
      with_items: '{{ all_services }}'
    # user services
    - name: create systemd start timer files
      template:
        src: templates/systemd.timer
        dest: '{{ user_config.systemd_unit_dir }}/{{ item }}.timer'
        mode: 0644
        owner: '{{ "root" if systemd_config.scope == "system" else ansible_user }}'
        group: '{{ "root" if systemd_config.scope == "system" else ansible_user }}'
      with_items: '{{ user_services }}'
      when: '"start" in conda_config.systemd.timers'
    - name: remove systemd start timer files
      file:
        path: '{{ user_config.systemd_unit_dir }}/{{ item }}.timer'
        state: absent
      with_items: '{{ user_services }}'
      when: '"start" not in conda_config.systemd.timers'
    - name: create systemd stop service files
      template:
        src: templates/systemd-stop.service
        dest: '{{ user_config.systemd_unit_dir }}/{{ item }}-stop.service'
        mode: 0644
        owner: '{{ "root" if systemd_config.scope == "system" else ansible_user }}'
        group: '{{ "root" if systemd_config.scope == "system" else ansible_user }}'
      with_items: '{{ user_services }}'
      when: '"stop" in conda_config.systemd.timers'
    - name: remove systemd stop service files
      file:
        path: '{{ user_config.systemd_unit_dir }}/{{ item }}-stop.service'
        state: absent
      with_items: '{{ user_services }}'
      when: '"stop" not in conda_config.systemd.timers'
    - name: create systemd stop timer files
      template:
        src: templates/systemd-stop.timer
        dest: '{{ user_config.systemd_unit_dir }}/{{ item }}-stop.timer'
        mode: 0644
        owner: '{{ "root" if systemd_config.scope == "system" else ansible_user }}'
        group: '{{ "root" if systemd_config.scope == "system" else ansible_user }}'
      with_items: '{{ user_services }}'
      when: '"stop" in conda_config.systemd.timers'
    - name: remove systemd stop timer files
      file:
        path: '{{ user_config.systemd_unit_dir }}/{{ item }}-stop.timer'
        state: absent
      with_items: '{{ user_services }}'
      when: '"stop" not in conda_config.systemd.timers'
    - name: enable/disable systemd services
      systemd:
        name: '{{ item }}.service'
        scope: '{{ systemd_config.scope }}'
        enabled: '{{ systemd_config.profiles[conda_config.systemd.profile].enabled }}'
        daemon_reload: true
      with_items: '{{ user_services }}'
    - name: enable systemd start timers
      systemd:
        name: '{{ item }}.timer'
        scope: '{{ systemd_config.scope }}'
        state: started
        enabled: true
        daemon_reload: true
      with_items: '{{ user_services }}'
      when: '"start" in conda_config.systemd.timers'
    - name: disable systemd stop services
      systemd:
        name: '{{ item }}-stop.service'
        scope: '{{ systemd_config.scope }}'
        enabled: false
        daemon_reload: true
      with_items: '{{ user_services }}'
      when: '"stop" in conda_config.systemd.timers'
    - name: enable systemd stop timers
      systemd:
        name: '{{ item }}-stop.timer'
        scope: '{{ systemd_config.scope }}'
        state: started
        enabled: true
        daemon_reload: true
      with_items: '{{ user_services }}'
      when: '"stop" in conda_config.systemd.timers'
    # service-manager services
    - name: enable/disable systemd services
      systemd:
        name: '{{ item }}.service'
        scope: '{{ systemd_config.scope }}'
        enabled: true
        daemon_reload: true
        state: started
      with_items: '{{ service_manager_services }}'
  become: '{{ systemd_config.scope == "system" }}'
  tags:
    - services
