global:
  scrape_interval: 5s

rule_files:
  - 'alert.rules'

alerting:
  alertmanagers:
    - scheme: http
      path_prefix: /alertmanager
      static_configs:
        - targets: ['alertmanager.service:{{ alertmanager_config.port }}']

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus.service:{{ prometheus_config.port }}']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter.service:{{ node_exporter_config.port }}']
{% if 'trading' in groups %}

  - job_name: 'clickhouse'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['clickhouse-server.service:{{ clickhouse_config.metrics_port }}']
{% endif %}
{% if 'roq_clickhouse' in groups %}

  - job_name: 'roq-clickhouse'
    metrics_path: '/roq/clickhouse/metrics'
    params:
      format: [ prometheus ]
    static_configs:
      - targets: ['nginx.service:{{ nginx_config.http_port }}']
{% endif %}
{% if 'roq_pubsub' in groups %}

  - job_name: 'roq-pubsub'
    metrics_path: '/roq/gateway/pubsub/metrics'
    params:
      format: [ prometheus ]
    static_configs:
      - targets: ['nginx.service:{{ nginx_config.http_port }}']
{% endif %}
{% if 'roq_json_bridge' in groups %}

  - job_name: 'roq-json-bridge'
    metrics_path: '/roq/gateway/json-bridge/metrics'
    params:
      format: [ prometheus ]
    static_configs:
      - targets: ['nginx.service:{{ nginx_config.http_port }}']
{% endif %}
{% if 'roq_fix_bridge' in groups %}

  - job_name: 'roq-fix-bridge'
    metrics_path: '/roq/gateway/fix-bridge/metrics'
    params:
      format: [ prometheus ]
    static_configs:
      - targets: ['nginx.service:{{ nginx_config.http_port }}']
{% endif %}
{% if 'roq_binance' in groups %}

  - job_name: 'roq-binance'
    metrics_path: '/roq/gateway/binance/metrics'
    params:
      format: [ prometheus ]
    static_configs:
      - targets: ['nginx.service:{{ nginx_config.http_port }}']
{% endif %}
{% if 'roq_binance_futures' in groups %}

  - job_name: 'roq-binance-futures'
    metrics_path: '/roq/gateway/binance-futures/metrics'
    params:
      format: [ prometheus ]
    static_configs:
      - targets: ['nginx.service:{{ nginx_config.http_port }}']
{% endif %}
{% if 'roq_bitfinex' in groups %}

  - job_name: 'roq-bitfinex'
    metrics_path: '/roq/gateway/bitfinex/metrics'
    params:
      format: [ prometheus ]
    static_configs:
      - targets: ['nginx.service:{{ nginx_config.http_port }}']
{% endif %}
{% if 'roq_bitmex' in groups %}

  - job_name: 'roq-bitmex'
    metrics_path: '/roq/gateway/bitmex/metrics'
    params:
      format: [ prometheus ]
    static_configs:
      - targets: ['nginx.service:{{ nginx_config.http_port }}']
{% endif %}
{% if 'roq_bitstamp' in groups %}

  - job_name: 'roq-bitstamp'
    metrics_path: '/roq/gateway/bitstamp/metrics'
    params:
      format: [ prometheus ]
    static_configs:
      - targets: ['nginx.service:{{ nginx_config.http_port }}']
{% endif %}
{% if 'roq_bybit' in groups %}

  - job_name: 'roq-bybit'
    metrics_path: '/roq/gateway/bybit/metrics'
    params:
      format: [ prometheus ]
    static_configs:
      - targets: ['nginx.service:{{ nginx_config.http_port }}']
{% endif %}
{% if 'roq_bybit_futures' in groups %}

  - job_name: 'roq-bybit-futures'
    metrics_path: '/roq/gateway/bybit-futures/metrics'
    params:
      format: [ prometheus ]
    static_configs:
      - targets: ['nginx.service:{{ nginx_config.http_port }}']
{% endif %}
{% if 'roq_coinbase_pro' in groups %}

  - job_name: 'roq-coinbase-pro'
    metrics_path: '/roq/gateway/coinbase-pro/metrics'
    params:
      format: [ prometheus ]
    static_configs:
      - targets: ['nginx.service:{{ nginx_config.http_port }}']
{% endif %}
{% if 'roq_deribit' in groups %}

  - job_name: 'roq-deribit'
    metrics_path: '/roq/gateway/deribit/metrics'
    params:
      format: [ prometheus ]
    static_configs:
      - targets: ['nginx.service:{{ nginx_config.http_port }}']
{% endif %}
{% if 'roq_ftx' in groups %}

  - job_name: 'roq-ftx'
    metrics_path: '/roq/gateway/ftx/metrics'
    params:
      format: [ prometheus ]
    static_configs:
      - targets: ['nginx.service:{{ nginx_config.http_port }}']
{% endif %}
{% if 'roq_gate' in groups %}

  - job_name: 'roq-gate'
    metrics_path: '/roq/gateway/gate/metrics'
    params:
      format: [ prometheus ]
    static_configs:
      - targets: ['nginx.service:{{ nginx_config.http_port }}']
{% endif %}
{% if 'roq_gate_futures' in groups %}

  - job_name: 'roq-gate-futures'
    metrics_path: '/roq/gateway/gate-futures/metrics'
    params:
      format: [ prometheus ]
    static_configs:
      - targets: ['nginx.service:{{ nginx_config.http_port }}']
{% endif %}
{% if 'roq_gemini' in groups %}

  - job_name: 'roq-gemini'
    metrics_path: '/roq/gateway/gemini/metrics'
    params:
      format: [ prometheus ]
    static_configs:
      - targets: ['nginx.service:{{ nginx_config.http_port }}']
{% endif %}
{% if 'roq_hitbtc' in groups %}

  - job_name: 'roq-hitbtc'
    metrics_path: '/roq/gateway/hitbtc/metrics'
    params:
      format: [ prometheus ]
    static_configs:
      - targets: ['nginx.service:{{ nginx_config.http_port }}']
{% endif %}
{% if 'roq_huobi' in groups %}

  - job_name: 'roq-huobi'
    metrics_path: '/roq/gateway/huobi/metrics'
    params:
      format: [ prometheus ]
    static_configs:
      - targets: ['nginx.service:{{ nginx_config.http_port }}']
{% endif %}
{% if 'roq_huobi_futures' in groups %}

  - job_name: 'roq-huobi-futures'
    metrics_path: '/roq/gateway/huobi-futures/metrics'
    params:
      format: [ prometheus ]
    static_configs:
      - targets: ['nginx.service:{{ nginx_config.http_port }}']
{% endif %}
{% if 'roq_kraken' in groups %}

  - job_name: 'roq-kraken'
    metrics_path: '/roq/gateway/kraken/metrics'
    params:
      format: [ prometheus ]
    static_configs:
      - targets: ['nginx.service:{{ nginx_config.http_port }}']
{% endif %}
{% if 'roq_kraken_futures' in groups %}

  - job_name: 'roq-kraken-futures'
    metrics_path: '/roq/gateway/kraken-futures/metrics'
    params:
      format: [ prometheus ]
    static_configs:
      - targets: ['nginx.service:{{ nginx_config.http_port }}']
{% endif %}
{% if 'roq_kucoin' in groups %}

  - job_name: 'roq-kucoin'
    metrics_path: '/roq/gateway/kucoin/metrics'
    params:
      format: [ prometheus ]
    static_configs:
      - targets: ['nginx.service:{{ nginx_config.http_port }}']
{% endif %}
{% if 'roq_kucoin_futures' in groups %}

  - job_name: 'roq-kucoin-futures'
    metrics_path: '/roq/gateway/kucoin-futures/metrics'
    params:
      format: [ prometheus ]
    static_configs:
      - targets: ['nginx.service:{{ nginx_config.http_port }}']
{% endif %}
{% if 'roq_okx' in groups %}

  - job_name: 'roq-okx'
    metrics_path: '/roq/gateway/okx/metrics'
    params:
      format: [ prometheus ]
    static_configs:
      - targets: ['nginx.service:{{ nginx_config.http_port }}']
{% endif %}
