global:
  scrape_interval: 5s

rule_files:
  - 'alert.rules'

alerting:
  alertmanagers:
    - scheme: http
      path_prefix: /alertmanager
      static_configs:
        - targets: ['alertmanager.service:{{ alertmanager_config.port }}']

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus.service:{{ prometheus_config.port }}']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter.service:{{ node_exporter_config.port }}']
{% if 'trading' in groups %}

  - job_name: 'clickhouse'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['clickhouse-server.service:{{ clickhouse_config.metrics_port }}']
{% endif %}
{% if 'roq_clickhouse' in groups %}

  - job_name: 'roq-clickhouse'
    metrics_path: '/metrics/roq-clickhouse'
    params:
      format: [ prometheus ]
    static_configs:
      - targets: ['nginx.service:{{ nginx_config.http_port }}']
{% endif %}
{% if 'roq_pubsub' in groups %}

  - job_name: 'roq-pubsub'
    metrics_path: '/metrics/roq-pubsub'
    params:
      format: [ prometheus ]
    static_configs:
      - targets: ['nginx.service:{{ nginx_config.http_port }}']
{% endif %}
{% if 'roq_json_bridge' in groups %}

  - job_name: 'roq-json-bridge'
    metrics_path: '/metrics/roq-json-bridge'
    params:
      format: [ prometheus ]
    static_configs:
      - targets: ['nginx.service:{{ nginx_config.http_port }}']
{% endif %}
{% if 'roq_fix_bridge' in groups %}

  - job_name: 'roq-fix-bridge'
    metrics_path: '/metrics/roq-fix-bridge'
    params:
      format: [ prometheus ]
    static_configs:
      - targets: ['nginx.service:{{ nginx_config.http_port }}']
{% endif %}
{% if 'roq_binance' in groups %}

  - job_name: 'roq-binance'
    metrics_path: '/metrics/roq-binance'
    params:
      format: [ prometheus ]
    static_configs:
      - targets: ['nginx.service:{{ nginx_config.http_port }}']
{% endif %}
{% if 'roq_binance_futures' in groups %}

  - job_name: 'roq-binance-futures'
    metrics_path: '/metrics/roq-binance-futures'
    params:
      format: [ prometheus ]
    static_configs:
      - targets: ['nginx.service:{{ nginx_config.http_port }}']
{% endif %}
{% if 'roq_bitmex' in groups %}

  - job_name: 'roq-bitmex'
    metrics_path: '/metrics/roq-bitmex'
    params:
      format: [ prometheus ]
    static_configs:
      - targets: ['nginx.service:{{ nginx_config.http_port }}']
{% endif %}
{% if 'roq_bitstamp' in groups %}

  - job_name: 'roq-bitstamp'
    metrics_path: '/metrics/roq-bitstamp'
    params:
      format: [ prometheus ]
    static_configs:
      - targets: ['nginx.service:{{ nginx_config.http_port }}']
{% endif %}
{% if 'roq_bybit' in groups %}

  - job_name: 'roq-bybit'
    metrics_path: '/metrics/roq-bybit'
    params:
      format: [ prometheus ]
    static_configs:
      - targets: ['nginx.service:{{ nginx_config.http_port }}']
{% endif %}
{% if 'roq_bybit_futures' in groups %}

  - job_name: 'roq-bybit-futures'
    metrics_path: '/metrics/roq-bybit-futures'
    params:
      format: [ prometheus ]
    static_configs:
      - targets: ['nginx.service:{{ nginx_config.http_port }}']
{% endif %}
{% if 'roq_coinbase_pro' in groups %}

  - job_name: 'roq-coinbase-pro'
    metrics_path: '/metrics/roq-coinbase-pro'
    params:
      format: [ prometheus ]
    static_configs:
      - targets: ['nginx.service:{{ nginx_config.http_port }}']
{% endif %}
{% if 'roq_deribit' in groups %}

  - job_name: 'roq-deribit'
    metrics_path: '/metrics/roq-deribit'
    params:
      format: [ prometheus ]
    static_configs:
      - targets: ['nginx.service:{{ nginx_config.http_port }}']
{% endif %}
{% if 'roq_ftx' in groups %}

  - job_name: 'roq-ftx'
    metrics_path: '/metrics/roq-ftx'
    params:
      format: [ prometheus ]
    static_configs:
      - targets: ['nginx.service:{{ nginx_config.http_port }}']
{% endif %}
{% if 'roq_gemini' in groups %}

  - job_name: 'roq-gemini'
    metrics_path: '/metrics/roq-gemini'
    params:
      format: [ prometheus ]
    static_configs:
      - targets: ['nginx.service:{{ nginx_config.http_port }}']
{% endif %}
{% if 'roq_hitbtc' in groups %}

  - job_name: 'roq-hitbtc'
    metrics_path: '/metrics/roq-hitbtc'
    params:
      format: [ prometheus ]
    static_configs:
      - targets: ['nginx.service:{{ nginx_config.http_port }}']
{% endif %}
{% if 'roq_huobi' in groups %}

  - job_name: 'roq-huobi'
    metrics_path: '/metrics/roq-huobi'
    params:
      format: [ prometheus ]
    static_configs:
      - targets: ['nginx.service:{{ nginx_config.http_port }}']
{% endif %}
{% if 'roq_huobi_futures' in groups %}

  - job_name: 'roq-huobi-futures'
    metrics_path: '/metrics/roq-huobi-futures'
    params:
      format: [ prometheus ]
    static_configs:
      - targets: ['nginx.service:{{ nginx_config.http_port }}']
{% endif %}
{% if 'roq_kraken' in groups %}

  - job_name: 'roq-kraken'
    metrics_path: '/metrics/roq-kraken'
    params:
      format: [ prometheus ]
    static_configs:
      - targets: ['nginx.service:{{ nginx_config.http_port }}']
{% endif %}
{% if 'roq_kraken_futures' in groups %}

  - job_name: 'roq-kraken-futures'
    metrics_path: '/metrics/roq-kraken-futures'
    params:
      format: [ prometheus ]
    static_configs:
      - targets: ['nginx.service:{{ nginx_config.http_port }}']
{% endif %}
{% if 'roq_kucoin' in groups %}

  - job_name: 'roq-kucoin'
    metrics_path: '/metrics/roq-kucoin'
    params:
      format: [ prometheus ]
    static_configs:
      - targets: ['nginx.service:{{ nginx_config.http_port }}']
{% endif %}
{% if 'roq_kucoin_futures' in groups %}

  - job_name: 'roq-kucoin-futures'
    metrics_path: '/metrics/roq-kucoin-futures'
    params:
      format: [ prometheus ]
    static_configs:
      - targets: ['nginx.service:{{ nginx_config.http_port }}']
{% endif %}
{% if 'roq_okex' in groups %}

  - job_name: 'roq-okex'
    metrics_path: '/metrics/roq-okex'
    params:
      format: [ prometheus ]
    static_configs:
      - targets: ['nginx.service:{{ nginx_config.http_port }}']
{% endif %}
