---

roq_json_bridge_defaults:
  version: "{{ roq_version }}"
  docker:
    use: "{{ roq_use_docker }}"
    name: "roqtrading/roq-json-bridge"
  service:
    start: "Sun *-*-* 00:01:00"
    stop: "Sat *-*-* 23:59:00"
  logging:
    verbosity: 0
  flags:
    name: "json-bridge"
    config_file: "{{ directory_config.usr_local_etc }}/roq/json-bridge/config.toml"
    client_listen_address: "{{ directory_config.run }}/roq/client/json-bridge.sock"
    service_listen_address: "{{ directory_config.run }}/roq/service/json-bridge.sock"
  symbols:
    - ".*"
  users: {}
